# These are supported funding model platforms

github: [nilupulk]
# patreon: your_patreon_username
# open_collective: your_open_collective_username
# ko_fi: your_kofi_username
# buymeacoffee: your_bmc_username
# custom: ['https://your-custom-funding-link.com']
